[tool.poetry]
name = "hass-miner"
version = "0.1.0"
description = ""
authors = ["Upstream Data <brett@upstreamdata.ca>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12.0,<3.14"
homeassistant = "^2024.12.5"
colorlog = "^6.9.0"
ruff = "^0.8.4"
pyasic = "^0.67.2"
setuptools = "^75.6.0"
pre-commit = "^4.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
