reboot:
  fields:
    mac:
      required: true
      example: 01:23:45:67:89:00
      selector:
        text:

restart_backend:
  fields:
    mac:
      required: true
      example: 01:23:45:67:89:00
      selector:
        text: