reboot:
  fields:
    ip:
      required: true
      example: 192.168.1.60
      selector:
        text:

restart_backend:
  fields:
    ip:
      required: true
      example: 192.168.1.60
      selector:
        text: